Bugfixes on compile.
Working out the kinks; had some missing brackets and rogue commas,
semicolons. However, now on compile I get:

    In file included from /usr/include/c++/4.9.2/random:35:0,
                from DIMS.cpp:27:
    /usr/include/c++/4.9.2/bits/c++0x_warning.h:32:2: error: #error This
    file requires compiler and library support for the ISO C++ 2011
    standard. This support is currently experimental, and must be enabled
    with the -std=c++11 or -std=gnu++11 compiler options.
     #error This file requires compiler and library support for the \
      ^

Does PLUMED2 support the C++11 standard?